# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
development:
  encoding: unicode
  adapter: postgresql
  database: transparency
  host: localhost
  port: 5432

test: &test
  encoding: unicode
  adapter: postgresql
  database: transparency_test
  host: localhost
  port: 5432
  min_messages: warning
